FROM resin/armv7hf-systemd:latest

ENV INITSYSTEM=on

RUN apt-get update \
	&& apt-get -y install xserver-common xserver-xorg-core xserver-xorg-input-all \
	&& apt-get -y install xorg kmod \
	&& apt-get -y install xscreensaver xscreensaver-data xscreensaver-data-extra xscreensaver-screensaver-bsod xscreensaver-screensaver-webcollage \
	&& rm -rf /var/lib/apt/*

WORKDIR /usr/src/app
COPY . ./

CMD /usr/src/app/go.sh
